import {
  ALargeSmall,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Bold,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Code,
  Columns3,
  Highlighter,
  Image,
  IndentDecrease,
  IndentIncrease,
  Italic,
  Link,
  List,
  ListChecks,
  ListOrdered,
  Maximize,
  Minimize,
  Minus,
  MoreHorizontal,
  Pilcrow,
  Quote,
  Redo2,
  RotateCcw,
  Rows3,
  Search,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCellsMerge,
  TableCellsSplit,
  Trash2,
  Type,
  Underline,
  Undo2,
  UploadCloud,
  Video,
  X,
  createElement,
  type IconNode,
} from "lucide";
import { editorText } from "@/editor/locale";

const icons = {
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strike: Strikethrough,
  code: Code,
  quote: Quote,
  list: List,
  orderedList: ListOrdered,
  taskList: ListChecks,
  rule: Minus,
  outdent: IndentDecrease,
  indent: IndentIncrease,
  link: Link,
  table: Table,
  image: Image,
  video: Video,
  undo: Undo2,
  redo: Redo2,
  more: MoreHorizontal,
  close: X,
  upload: UploadCloud,
  retry: RotateCcw,
  remove: Trash2,
  check: Check,
  down: ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  justify: AlignJustify,
  text: Type,
  size: ALargeSmall,
  highlight: Highlighter,
  paragraph: Pilcrow,
  rows: Rows3,
  columns: Columns3,
  merge: TableCellsMerge,
  split: TableCellsSplit,
  search: Search,
  fullscreen: Maximize,
  exitFullscreen: Minimize,
  subscript: Subscript,
  superscript: Superscript,
} satisfies Record<string, IconNode>;

export type EditorIcon = keyof typeof icons;

export function editorIcon(name: EditorIcon): SVGElement {
  return createElement(icons[name], {
    width: 18,
    height: 18,
    "stroke-width": 1.8,
    "aria-hidden": "true",
    focusable: "false",
    class: "jwsoft-icon",
  });
}

const labels: Record<string, EditorIcon> = {
  굵게: "bold",
  기울임: "italic",
  밑줄: "underline",
  취소선: "strike",
  코드: "code",
  인용: "quote",
  목록: "list",
  번호: "orderedList",
  구분선: "rule",
  내어쓰기: "outdent",
  들여쓰기: "indent",
  링크: "link",
  표: "table",
  이미지: "image",
  동영상: "video",
  "링크 카드": "link",
  실행취소: "undo",
  다시실행: "redo",
  "행+": "rows",
  "행−": "rows",
  "열+": "columns",
  "열−": "columns",
  "표 삭제": "remove",
};

export function iconForLabel(label: string): EditorIcon | undefined {
  return (
    labels[label] ??
    Object.entries(labels).find(([key]) => editorText("en", key) === label)?.[1]
  );
}
