import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import prettier from "prettier";

const root = path.resolve(import.meta.dirname, "..");
const policyPath = path.join(root, "policy/editor-policy.json");
const policySource = fs.readFileSync(policyPath, "utf8");
const policy = JSON.parse(policySource);
const policyHash = crypto
  .createHash("sha256")
  .update(policySource)
  .digest("hex");
const checkOnly = process.argv.includes("--check");

const allowedTags = Object.keys(policy.elements);
const allowedAttributes = [
  ...new Set([
    ...policy.globalAttributes,
    ...Object.values(policy.elements).flatMap(({ attributes }) => attributes),
  ]),
].sort();
const classTokens = [
  ...new Set(Object.values(policy.classTokens).flat()),
].sort();

const domPurifyConfig = {
  ALLOWED_TAGS: allowedTags,
  ALLOWED_ATTR: allowedAttributes,
  ALLOW_DATA_ATTR: false,
  ALLOW_ARIA_ATTR: false,
  FORBID_ATTR: ["id", "style"],
};

const tokenCss = `
.jw-text-sm { font-size: 0.875rem; }
.jw-text-base { font-size: 1rem; }
.jw-text-lg { font-size: 1.125rem; }
.jw-text-xl { font-size: 1.25rem; }
.jw-align-left { text-align: left; }
.jw-align-center { text-align: center; }
.jw-align-right { text-align: right; }
.jw-space-tight { line-height: 1.35; }
.jw-space-normal { line-height: 1.7; }
.jw-space-relaxed { line-height: 2; }
.jw-table { width: 100%; border-collapse: collapse; }
.jw-table-striped tbody tr:nth-child(odd) { background: rgb(249 250 251); }
.jw-image-inline { display: inline-block; }
.jw-image-block { display: block; margin-inline: auto; }
.jw-image-rounded { border-radius: 0.5rem; }
.jw-media { position: relative; width: min(100%, 60rem); margin: 1rem auto; overflow: hidden; border-radius: 0.625rem; background: #111827; color: #fff; }
.jw-media-16x9 { aspect-ratio: 16 / 9; }
.jw-media-9x16 { width: min(100%, 26rem); aspect-ratio: 9 / 16; }
.jw-media-source, .jw-media-load, .jw-media-player { position: absolute; inset: 0; box-sizing: border-box; width: 100%; height: 100%; }
.jw-media-source, .jw-media-load { display: grid; place-items: center; border: 0; padding: 1rem; background: #111827; color: #fff; text-align: center; text-decoration: none; cursor: pointer; }
.jw-media-source:hover, .jw-media-load:hover { background: #1f2937; }
.jw-media-player { border: 0; background: #000; }
`.trim();

function phpQuote(value) {
  return `'${String(value).replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
}

function phpExport(value, indent = 0) {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return phpQuote(value);

  const pad = " ".repeat(indent);
  const childPad = " ".repeat(indent + 4);
  const entries = Array.isArray(value)
    ? value.map((item) => `${childPad}${phpExport(item, indent + 4)},`)
    : Object.entries(value).map(
        ([key, item]) =>
          `${childPad}${phpQuote(key)} => ${phpExport(item, indent + 4)},`,
      );

  return entries.length ? `[\n${entries.join("\n")}\n${pad}]` : "[]";
}

const tsSource = await prettier.format(
  `// Generated by scripts/generate-policy.mjs. Do not edit.
export const EDITOR_POLICY_HASH = ${JSON.stringify(policyHash)} as const;
export const EDITOR_POLICY = ${JSON.stringify(policy)} as const;
export const EDITOR_ALLOWED_TAGS = ${JSON.stringify(allowedTags)} as const;
export const EDITOR_ALLOWED_ATTRIBUTES = ${JSON.stringify(allowedAttributes)} as const;
export const EDITOR_CLASS_TOKENS = ${JSON.stringify(classTokens)} as const;
export const EDITOR_DOMPURIFY_CONFIG = ${JSON.stringify(domPurifyConfig)} as const;
export const EDITOR_TOKEN_CSS = ${JSON.stringify(tokenCss)} as const;
`,
  { parser: "typescript" },
);

const phpSource = `<?php

namespace Plugins\\Jwsoft\\TiptapEditor\\Generated;

/** Generated by scripts/generate-policy.mjs. Do not edit. */
final class EditorPolicy
{
    public const SHA256 = ${phpQuote(policyHash)};

    public const POLICY = ${phpExport(policy, 4)};
}
`;

const domPurifySource = await prettier.format(
  `${JSON.stringify(domPurifyConfig)}\n`,
  { parser: "json" },
);

const extensionPath = path.join(root, "resources/extensions/html-content.json");
const extension = JSON.parse(fs.readFileSync(extensionPath, "utf8"));
const htmlContent = extension.components.find(
  ({ name, type }) => name === "HtmlContent" && type === "composite",
);
if (!htmlContent?.props) {
  throw new Error(
    "html-content extension에서 HtmlContent props를 찾을 수 없습니다.",
  );
}
htmlContent.props.purifyConfig = domPurifyConfig;
const extensionSource = await prettier.format(
  `${JSON.stringify(extension)}\n`,
  {
    parser: "json",
  },
);

const outputs = new Map([
  ["resources/js/generated/editorPolicy.ts", tsSource],
  ["resources/generated/dompurify-config.json", domPurifySource],
  ["src/Generated/EditorPolicy.php", phpSource],
  ["resources/extensions/html-content.json", extensionSource],
]);

let stale = false;
for (const [relativePath, contents] of outputs) {
  const outputPath = path.join(root, relativePath);
  if (checkOnly) {
    if (
      !fs.existsSync(outputPath) ||
      fs.readFileSync(outputPath, "utf8") !== contents
    ) {
      console.error(`[jwsoft] policy 파생물이 오래되었습니다: ${relativePath}`);
      stale = true;
    }
    continue;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, contents);
}

if (stale) process.exit(1);
console.log(
  checkOnly
    ? "[jwsoft] Editor policy 파생물 동기화 검사 통과"
    : "[jwsoft] Editor policy 파생물 생성 완료",
);
